### ISSUE TITLE
Parse traffic

### ISSUE THREAD

**Issue by Andrioden** [Andrioden/CEPGP-Parser#3]
# TODO
- [x] ~~CEPGP.Traffic  (also in TRAFFIC)~~
- [x] TRAFFIC
- [x] Handle all formats
  - [x] Also think i saw the new format with string wrapped dates

# Formats

## Current
1 = Player
2 = IssuedBy
3 = Action
4 = Ep before
5 = Ep after
6 = Gp before
7 = Gp after
8 = Item with item-ingame-link info
9 = Date GMT+0
10 = Unknown - Sync field? ?? Shows date in the future ??
11 = Unknown - Sync field ?

``` lua
{
	"Fosen", -- [1]
	"Andriod", -- [2]
	"Add GP 450 (Full Price)", -- [3]
	409, -- [4]
	409, -- [5]
	164, -- [6]
	614, -- [7]
	"|cffa335ee|Hitem:21581:::::::::::::|h[Gauntlets of Annihilation]|h|r", -- [8]
	1600635769, -- [9]
	1600980162.066, -- [10]
	"Player-4676-01808E8E", -- [11]
}, -- [5034]
```

## Old
``` lua
{
	"Aech", -- [1]
	"Andriod", -- [2]
	"Add EP +22 (Raid 30.09.2019)", -- [3]
	0, -- [4]
	22, -- [5]
	1, -- [6]
	1, -- [7]
}, -- [1]
```

## Old - with item
``` lua
{
	"Devnant", -- [1]
	"Snikur", -- [2]
	"Add GP +200", -- [3]
	"95", -- [4]
	"95", -- [5]
	"291", -- [6]
	"491", -- [7]
	"|cffa335ee|Hitem:16914::::::::110:::::|h[Netherwind Crown]|h|r", -- [8]
}, -- [174]
```

## Old - with item and date as int epoch
``` lua
{
	"", -- [1]
	"Snikur", -- [2]
	"Not EPGP Moderated", -- [3]
	"107", -- [4]
	"107", -- [5]
	"380", -- [6]
	"380", -- [7]
	"|cffa335ee|Hitem:16823:::::::::::::|h[Nightslayer Shoulder Pads]|h|r", -- [8]
	1579466815, -- [9]
}, -- [783]
```

## Old - with item and date as string epoch
``` lua
{
	"", -- [1]
	"Snikdale", -- [2]
	"Manually Awarded", -- [3]
	"", -- [4]
	"", -- [5]
	"", -- [6]
	"", -- [7]
	"|cffa335ee|Hitem:16807:::::::::::::|h[Felheart Shoulder Pads]|h|r", -- [8]
	"1581885547", -- [9]
}, -- [1030]
```

## [9] = Date bug?
I think it shows as no date in ingame gui. 
``` lua
{
	"Raid", -- [1]
	"Snikur", -- [2]
	"Add Raid EP +5 - Ragnaros", -- [3]
	"", -- [4]
	"", -- [5]
	"", -- [6]
	"", -- [7]
	[9] = 1580676719,
}, -- [903]
```
``` lua
{
	"Raid", -- [1]
	"Snikdale", -- [2]
	"Add Raid EP +1 - Baron Geddon", -- [3]
	"", -- [4]
	"", -- [5]
	"", -- [6]
	"", -- [7]
	[9] = "1581885508",
}, -- [1029]
```
